//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeopardyGame.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JeopardyGame.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $1000.
        /// </summary>
        internal static string _1000 {
            get {
                return ResourceManager.GetString("1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $1200.
        /// </summary>
        internal static string _1200 {
            get {
                return ResourceManager.GetString("1200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $1600.
        /// </summary>
        internal static string _1600 {
            get {
                return ResourceManager.GetString("1600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $200.
        /// </summary>
        internal static string _200 {
            get {
                return ResourceManager.GetString("200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $2000.
        /// </summary>
        internal static string _2000 {
            get {
                return ResourceManager.GetString("2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $400.
        /// </summary>
        internal static string _400 {
            get {
                return ResourceManager.GetString("400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $600.
        /// </summary>
        internal static string _600 {
            get {
                return ResourceManager.GetString("600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $800.
        /// </summary>
        internal static string _800 {
            get {
                return ResourceManager.GetString("800", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to J! Archive does not have a game for.
        /// </summary>
        internal static string MissingGame {
            get {
                return ResourceManager.GetString("MissingGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mystery.
        /// </summary>
        internal static string Mystery {
            get {
                return ResourceManager.GetString("Mystery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔈_Play Music.
        /// </summary>
        internal static string PlayMusic {
            get {
                return ResourceManager.GetString("PlayMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔇_Stop Music.
        /// </summary>
        internal static string StopMusic {
            get {
                return ResourceManager.GetString("StopMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrevealed.
        /// </summary>
        internal static string Unrevealed {
            get {
                return ResourceManager.GetString("Unrevealed", resourceCulture);
            }
        }
    }
}
